### ISSUE TITLE
Server Tick Loop

### ISSUE THREAD

**Issue by slidingmike** [vidaj/ExtraBlocks#1]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-beta-40.jar)
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  IC2core (industrialcraft-2-2.6.1-ex110.jar)
  FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.10-2.0.9.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.37-beta.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 08/07/16 12:14
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: com.extrablocksmod.ExtraBlocksMod$ServerProxy
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:88)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:557)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
    at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
    at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:328)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.extrablocksmod.ExtraBlocksMod$ServerProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:72)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:71)
    ... 27 more
Caused by: java.lang.NullPointerException
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Linux (amd64) version 3.14.32-xxxx-grs-ipv6-64
    Java Version: 1.8.0_74, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 211808632 bytes (201 MB) / 502136832 bytes (478 MB) up to 4080271360 bytes (3891 MB)
    JVM Flags: 34 total; -XX:+UseCompressedOops -XX:+UseAdaptiveGCBoundary -XX:+OptimizeStringConcat -XX:+UseLargePages -XX:CompileThreshold=1500 -XX:+UseFastAccessorMethods -Xmx4G -XX:ThreadPriorityPolicy=42 -XX:+UseThreadPriorities -XX:+UseParNewGC -XX:TargetSurvivorRatio=90 -XX:+UseGCOverheadLimit -XX:ParallelGCThreads=4 -XX:+UnlockExperimentalVMOptions -XX:+AggressiveOpts -XX:MaxTenuringThreshold=15 -XX:+TieredCompilation -XX:+UseStringCache -XX:+UseConcMarkSweepGC -XX:+UseBiasedLocking -Xnoclassgc -Xverify:none -XX:+UseLargePages -XX:NewRatio=3 -XX:SurvivorRatio=3 -XX:MaxTenuringThreshold=8 -XX:MaxGCPauseMillis=10 -XX:GCPauseIntervalMillis=50 -XX:MaxGCMinorPauseMillis=7 -XX:+ExplicitGCInvokesConcurrent -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=60 -XX:+BindGCTaskThreadsToCPUs -Xrs
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.0.2007 122 mods loaded, 122 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.0.2007-1.10.0-universal.jar) 
    UC  Forge{12.18.0.2007} [Minecraft Forge](forge-1.10.2-12.18.0.2007-1.10.0-universal.jar) 
    UC  buildingbrickshooks{1.10-2.0.9} [Building Bricks Hooks](minecraft.jar) 
    UC  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10-alpha-1.0.0.jar) 
    UC  JEI{3.7.5.227} [Just Enough Items](jei_1.10.2-3.7.5.227.jar) 
    UC  abyssalcraft{1.9.2.1} [AbyssalCraft](AbyssalCraft-1.10-1.9.2.1.jar) 
    UC  actuallyadditions{1.10.2-r49} [Actually Additions](ActuallyAdditions-1.10.2-r49.jar) 
    UC  agriculturalexpansion{r-1.2.0} [Agricultural Expansion](AgriculturalExpansion[1.9.4][1.10.2]r-1.2.0.jar) 
    UC  AppleCore{1.3.5} [AppleCore](AppleCore-mc1.10.2-1.3.5.jar) 
    UC  autopackager{1.6.3} [AutoPackager](autopackager-1.6.3.jar) 
    UC  bagginses{2.4.2d} [Bagginses](Bagginses-1.10-3.0.2.jar) 
    UC  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UC  BBG{5.0.0} [BetterBedrockGen](BBG-1.9.4-5.0.0.jar) 
    UC  bdlib{1.12.0.2} [BD Lib](bdlib-1.12.0.2-mc1.10.2.jar) 
    UC  BetterAchievements{0.3.0.28} [Better Achievements](BetterAchievements-1.10.2-0.3.0.28.jar) 
    UC  betterbuilderswands{0.6.5} [Better Builder's Wands](BetterBuildersWands-0.6.5-1.10r1388595fc7.jar) 
    UC  BloodMagic{1.9.4-2.0.2-50} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9.4-2.0.2-50.jar) 
    UC  BloodArsenal{1.9.4-2.0.0-10} [Blood Arsenal](BloodArsenal-1.9.4-2.0.0-10.jar) 
    UC  boilerplate{1.9.4-8.2.3} [Boilerplate](Boilerplate-1.9.4-8.2.3-universal.jar) 
    UC  bookshelfapi{3.1.0} [Bookshelf](Bookshelf-API-1.9.4-3.1.0.jar) 
    UC  Botania{r1.8-312} [Botania](Botania-unofficial.r1.8-312.jar) 
    UC  Quark{beta-40} [Quark](Quark-beta-40.jar) 
    UC  buildingbricks{1.10-2.0.9} [Building Bricks](BuildingBricks-1.10-2.0.9.jar) 
    UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UC  SonarCore{3.0.2} [SonarCore](SonarCore-1.9.4-3.0.2.jar) 
    UC  Calculator{3.0.2} [Calculator](Calculator-1.9.4-3.0.2.jar) 
    UC  canijoinnow{@VERSION@} [Can I Join Now?](CanIJoinNow-1.9.4-1.0-3.jar) 
    UC  capsule{1.9.4-1.1.7} [Capsule](Capsule-1.9.4-1.1.7.jar) 
    UC  Chameleon{1.9.4-2.1.5} [Chameleon](Chameleon-1.9.4-2.1.5.jar) 
    UC  mcmultipart{1.2.0} [MCMultiPart](MCMultiPart-1.2.0-universal.jar) 
    UC  CharsetLib{0.3.0-pre12} [‽](Charset-0.3.0-pre12.jar) 
    UC  CharsetAudio{0.3.0-pre12} [♫](Charset-0.3.0-pre12.jar) 
    UC  CharsetCarts{0.3.0-pre12} [U](Charset-0.3.0-pre12.jar) 
    UC  CharsetDecoration{0.3.0-pre12} [�?](Charset-0.3.0-pre12.jar) 
    UC  CharsetDrama{0.3.0-pre12} [!](Charset-0.3.0-pre12.jar) 
    UC  CharsetFarming{0.3.0-pre12} [;](Charset-0.3.0-pre12.jar) 
    UC  CharsetGates{0.3.0-pre12} [&](Charset-0.3.0-pre12.jar) 
    UC  CharsetPipes{0.3.0-pre12} [|](Charset-0.3.0-pre12.jar) 
    UC  CharsetStorage{0.3.0-pre12} [#](Charset-0.3.0-pre12.jar) 
    UC  CharsetTweaks{0.3.0-pre12} [*](Charset-0.3.0-pre12.jar) 
    UC  CharsetWires{0.3.0-pre12} [+](Charset-0.3.0-pre12.jar) 
    UC  CharsetWrench{0.3.0-pre12} [/](Charset-0.3.0-pre12.jar) 
    UC  ChestTransporter{2.5.0} [Chest Transporter](ChestTransporter-1.10-2.5.0.jar) 
    UC  chisel{@VERSION@} [Chisel](Chisel-MC1.9.4-0.0.5.29.jar) 
    UC  chiselsandbits{11.5} [Chisels & Bits](chiselsandbits-11.5.jar) 
    UC  cyclopscore{0.7.1} [Cyclops Core](CyclopsCore-1.9.4-0.7.1.jar) 
    UC  commoncapabilities{1.1.0} [CommonCapabilities](CommonCapabilities-1.9.4-1.1.0.jar) 
    UC  covers{0.3.0.3} [Simple Covers](covers-0.3.0.3-mc1.10.2.jar) 
    UC  craftingcraft{4.0.3} [CraftingCraft](craftingcraft-mc1.9.4-4.0.3.jar) 
    UC  craftingtweaks{5.0.6} [Crafting Tweaks](craftingtweaks-mc1.9.4-5.0.6.jar) 
    UC  MineTweaker3{3.0.10} [MineTweaker 3](CraftTweaker-1.10.2-3.0.10.jar) 
    UC  drones{1.10.2-1.0.2} [Drones](CustomDrones-1.0.2-mc1.10.2.jar) 
    UC  decoy{1.0.2} [Decoy](Decoy-1.9.4-1.0.2.jar) 
    UC  ElecCore{1.5.292} [ElecCore](ElecCore-1.9.4-1.5.292.jar) 
    UC  deepresonance{1.2.0beta35} [DeepResonance](deepresonance-1.9.4-1.2.0beta35.jar) 
    UC  elementsofpower{0.7.10-alpha} [Elements of Power](ElementsOfPower-1.9.4-0.7.10-alpha.jar) 
    UC  endercore{1.10.2-0.4.1.37-beta} [EnderCore](EnderCore-1.10.2-0.4.1.37-beta.jar) 
    UC  EnderIO{1.10-3.0.0.60_beta} [Ender IO](EnderIO-1.10-3.0.0.60_beta.jar) 
    UC  shetiphiancore{3.2.6} [ShetiPhian-Core](shetiphiancore-1.9.4-3.2.6.jar) 
    UC  endertanks{1.3.6} [EnderTanks](endertanks-1.9.4-1.3.6.jar) 
    UC  enderthing{0.6.8} [Enderthing](enderthing-1.9.4-0.6.8.jar) 
    UC  enderutilities{0.6.5-beta.1} [Ender Utilities](enderutilities-1.10.2-0.6.5-beta.1.jar) 
    UC  ValkyrieLib{1.10-0.10.1} [Valkyrie Lib](valkyrielib-1.10-0.10.1.jar) 
    UC  EnvironmentalTech{1.10-0.10.1a} [Environmental Tech](environmentaltech-1.10-0.10.1a.jar) 
    UE  extrablocks{1.0.0} [ExtraBlocks](extrablocks-1.0.0.jar) 
    UC  IC2{2.6.1-ex110} [IndustrialCraft 2](industrialcraft-2-2.6.1-ex110.jar) 
    UC  OpenComputers{1.6.0.2-beta.4} [OpenComputers](OpenComputers-MC1.10-1.6.0.2-beta.4.jar) 
    UC  FFS{1.9.4-1.6.4-b28} [Fancy Fluid Storage](Fancy Fluid Storage-1.9.4-1.6.4-b28.jar) 
    UC  fastleafdecay{v10} [Fast Leaf Decay](FastLeafDecay-v10.jar) 
    UC  flatcoloredblocks{mc1.10-v4.1} [Flat Colored Blocks](flatcoloredblocks-mc1.10-v4.1.jar) 
    UC  forestry{5.1.10.192} [Forestry](forestry_1.10.2-5.1.10.192.jar) 
    UC  substratum{1.6.0.1} [Substratum](Substratum-1.10.2-1.6.0.1.jar) 
    UC  foundry{2.0.0.1} [Foundry](Foundry-1.10.2-2.0.0.1.jar) 
    UC  ftbl{2.1.0} [FTBLib](FTBLib-1.9.4-2.1.0-pre2.jar) 
    UC  ftbu{2.1.0} [FTBUtilities](FTBUtilities-1.9.4-2.1.0-pre2.jar) 
    UC  gendustry{1.6.4.7} [GenDustry](gendustry-1.6.4.7-mc1.10.2.jar) 
    UC  pressure{1.3.1.3} [Pressure Pipes](pressure-1.3.1.3-mc1.10.2.jar) 
    UC  advgenerators{0.9.20.4} [Advanced Generators](generators-0.9.20.4-mc1.10.2.jar) 
    UC  fishing{1.4} [Fishing Net Mod](GiacomosFishingNet1.9.4-1.4.jar) 
    UC  LunatriusCore{1.1.2.36} [LunatriusCore](LunatriusCore-1.10.2-1.1.2.36-universal.jar) 
    UC  InGameInfoXML{2.8.1.85} [InGame Info XML](InGameInfoXML-1.10.2-2.8.1.85-universal.jar) 
    UC  integrateddynamics{0.4.0} [Integrated Dynamics](IntegratedDynamics-1.9.4-0.4.0.jar) 
    UC  inventorytweaks{1.61-beta-57-c028bbc} [Inventory Tweaks](InventoryTweaks-1.61-beta-57.jar) 
    UC  ircbridge{2.0.1} [IRCBridge](ircbridge-mc1.9.4-2.0.1.jar) 
    UC  IronChest{7.0.5.793} [Iron Chest](ironchest-1.10-7.0.5.793.jar) 
    UC  journeymap{1.10.2-5.2.4} [JourneyMap](journeymap-1.10.2-5.2.4-unlimited.jar) 
    UC  mantle{1.10-0.10.3.jenkins156} [Mantle](Mantle-1.10-0.10.3.jar) 
    UC  modtweaker2{2.0.0} [Mod Tweaker 2](ModTweaker2-2.0.0.jar) 
    UC  modularutilities{1.9.4-0.2.2} [Modular Utilities](ModularUtilities-1.9.4-0.2.2.jar) 
    UC  Morpheus{1.10-3.1.6} [Morpheus](Morpheus-1.10-3.1.6.jar) 
    UC  tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct](TConstruct-1.10-2.3.3a.jar) 
    UC  neotech{3.1.0} [NeoTech](NeoTech-1.9.4-3.1.0.jar) 
    UC  harvestcraft{1.9.4-pre} [Pam's HarvestCraft](Pams HarvestCraft 1.9.4c.jar) 
    UC  ping{1.2.2} [Ping](Ping-1.10.X-1.2.2.B7-universal.jar) 
    UC  gunpowder{1.1_1.9.4} [Placeable Gunpowder](PlaceableGunpowder-1.1_1.9.4.jar) 
    UC  progressiveautomation{1.6.48} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.48.jar) 
    UC  Psi{r1.0-36} [Psi](Psi-r1.0-36.jar) 
    UC  randomthings{3.7.4} [Random Things](RandomThings-MC1.10-3.7.4.jar) 
    UC  recallstones{0.6.2} [Recall Stones](RecallStones-1.10.2-0.6.2.jar) 
    UC  StorageDrawers{1.9.4-3.1.11} [Storage Drawers](StorageDrawers-1.9.4-3.1.11.jar) 
    UC  refinedstorage{0.8.5} [Refined Storage](refinedstorage-0.8.5.jar) 
    UC  xreliquary{1.10.2-1.3.2.419} [Reliquary](Reliquary-1.10.2-1.3.2.419.jar) 
    UC  rftools{5.03} [RFTools](rftools-1.10-5.03.jar) 
    UC  rftoolsdim{4.30beta45} [RFTools Dimensions](rftoolsdim-1.10-4.30beta45.jar) 
    UC  Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4.jar) 
    UC  roots{0.107} [Roots](roots-0.107.jar) 
    UC  Signals{1.0} [Signals](Signals-1.9.4-0.4.1-universal.jar) 
    UC  SolarFluxReborn{1.10.2_0.4b} [Solar Flux Reborn](SolarFluxReborn-1.10.2_0.4b.jar) 
    UC  soulshardstow{1.10-2.5.0-34} [Soul Shards - The Old Ways](SoulShards-TOW-1.10-2.5.0-34.jar) 
    UC  storagenetwork{1.12.3} [Storage Network](StorageNetwork-1.9.4-1.12.3.jar) 
    UC  tinker_io{beta 2.3.0c} [Tinker I/O](tinker_io-1.10-beta 2.3.0c.jar) 
    UC  tombmanygraves{1.9.4-2.1.6} [Tomb Many Graves](TombManyGraves-1.9.4-2.1.6.jar) 
    UC  trashslot{6.3.2} [TrashSlot](TrashSlot_1.10.2-6.3.2.jar) 
    UC  vampirism{1.0.0-Alpha+07-04-22-58} [Vampirism](Vampirism-1.10.2-1.0.0-Alpha07-04-22-58.jar) 
    UC  teamlapen-lib{1.0.0-Alpha+07-04-22-58} [TeamLapen Library](Vampirism-1.10.2-1.0.0-Alpha07-04-22-58.jar) 
    UC  VeinMiner{0.34.1_1.9-73be663} [Vein Miner](VeinMiner-0.34.1-1.9r57173be663.jar) 
    UC  VeinMinerModSupport{0.34.1_1.9-73be663} [Mod Support](VeinMiner-0.34.1-1.9r57173be663.jar) 
    UC  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.10-1.1.7.jar) 
    UC  ICSE{1.1.0.0} [I Can See Everything](Wawla-1.10-2.3.0.193.jar) 
    UC  wawla{2.3.0.193} [What Are We Looking At](Wawla-1.10-2.3.0.193.jar) 
    UC  UniDict{1.10.2-1.0} [UniDict](UniDict-1.10.2-1.0.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-beta-40.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
AppleCore (AppleCore-mc1.10.2-1.3.5.jar)
  squeek.applecore.asm.TransformerModuleHandler
IC2core (industrialcraft-2-2.6.1-ex110.jar)

FMLPlugin (InventoryTweaks-1.61-beta-57.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.10-2.0.9.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
EnderCorePlugin (EnderCore-1.10.2-0.4.1.37-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

```
Profiler Position: N/A (disabled)
Is Modded: Definitely; Server brand changed to 'fml,forge'
Type: Dedicated Server (map_server.txt)
```

**Comment by vidaj** [comment]
Sorry about that. Haven't set up my server to properly test this yet in multiplayer. I have pushed out v.1.0.2 that should fix this problem.

Thanks for the heads up.
